companies = {
        '^FCHI': '(Indice) CAC40',
        '^DJI': '(Indice) Dow Jones',
        '^GSPC': '(Indice) S&P500',
        '^IXIC': '(Indice) Nasdaq',
        '^NYA': '(Indice) NYSE',
        '^FTSE': '(Indice) FTSE100',
        'EURCHF=X': '(Devise) EUR/CHF',
        'BZ=F': '(Matière première) Pétrole Brent',
        'GC=F': '(Matière première) Or',
        'SI=F': '(Matière première) Argent',
        'ZC=F': '(Matière première) Maïs',
        'ZS=F': '(Matière première) Soja',
        'ZW=F': '(Matière première) Blé',
        'OJ=F': '(Matière première) Jus d\'orange',
        'SB=F': '(Matière première) Sucre',
        'MC.PA': 'LVMH',
        'OR.PA': 'L\'Oréal',
        'RMS.PA': 'Hermès',
        'TTE': 'Total',
        'CDI.PA': 'Christian Dior',
        'SNY': 'Sanofi',
        'SU.PA': 'Schneider Electric',
        'AI.PA': 'Air Liquide',
        'EL.PA': 'EssilorLuxottica',
        'BNP.PA': 'BNP Paribas',
        'SAF.PA': 'Safran',
        'CS.PA': 'AXA',
        'DG.PA': 'Vinci',
        'DSY.PA': 'Dassault Systèmes',
        'KER.PA': 'Kering',
        'ACA.PA': 'Crédit Agricole',
        'RI.PA': 'Pernod Ricard',
        'BN.PA': 'Danone',
        'CAP.PA': 'Capgemini',
        'SGO.PA': 'Saint-Gobain',
        'ORAN': 'Orange',
        'HO.PA': 'Thales',
        'LR.PA': 'Legrand',
        'PUB.PA': 'Publicis',
        'ML.PA': 'Michelin',
        'VIE.PA': 'Veolia',
        'GLE.PA': 'Société Générale',
        'BOP.F': 'Bolloré',
        'SW.PA': 'Sodexo',
        'EDEN.PA': 'Edenred',
        'AM.PA': 'Dassault Aviation',
        'AMUN.PA': 'Amundi',
        'BIM.PA': 'Biomerieux',
        'ADP.PA': 'Aéroports de Paris',
        'BVI.PA': 'Bureau Veritas',
        'CA.PA': 'Carrefour',
        'VIV.PA': 'Vivendi',
        'RNO.PA': 'Renault',
        'TEP.PA': 'Teleperformance',
        'FGR.PA': 'Eiffage',
        'AC.PA': 'Accor',
        'URW.AS': 'Unibail-Rodamco-Westfield',
        'IPN.PA': 'IPSEN',
        'GET.PA': 'Getlink',
        'GFC.PA': 'Gecina',
        'AKE.PA': 'Arkema',
        'RXL.PA': 'Rexel',
        'FDJ.VI': 'Française des Jeux',
        'LI.PA': 'Klépierre',
        'SK.PA': 'Groupe SEB',
        'RF.PA': 'Eurazeo',
        'RCO.PA': 'Remy Cointreau',
        'SPIE.PA': 'Spie',
        'ALD.PA': 'ALD',
        'SOI.PA': 'Sopra Steria',
        'ATE.PA': 'Alten',
        'SCR.PA': 'Scor',
        'ELIS.PA': 'Elis',
        'COV.PA': 'Covivio',
        'ALO.PA': 'Alstom',
        'DEC.PA': 'JCDecaux',
        'NEOEN.PA': 'Neoen',
        'WLN.PA': 'Worldline',
        'NEX.PA': 'Nexans',
        'TKO.PA': 'Tikehau Capital',
        'MF.PA' : 'Wendel',
        'AF.PA' : 'Air France-KLM',
        'FR.PA' : 'Valeo',
        'FLY.PA': 'Société Foncière Lyonnaise',
        'VIRP.PA': 'Virbac',
        'TRI.PA': 'Trigano',
        'BB.PA': 'BIC',
        'UBI.PA': 'Ubisoft',
        'NK.PA': 'Imerys',
        'CSTM' : 'Constellium',
        'MMB.PA': 'Lagardère',
        'ICAD.PA': 'Icade',
        'RUI.PA': 'RUBIS',
        'COVH.PA': 'Covivio Hotels',
        'ETL.PA':'Eutelsat',
        'OVH.PA':"OVH Groupe",
        'COFA.PA':'Coface',
        'ORP.PA':'Orpea',
        'EXN.PA':'Exclusive Networks',
        'TFI.PA':'TF1',
        'CBE.PA':'Robertet',
        'ALTA.PA':'Altarea',
        'MMT.PA':'Groupe M6',
        'POM.PA':'Plastic Omnium',
        'CRTO':'Criteo',
        'VLTSA.PA':'Voltalia',
        'BEN.PA':'Bénéteau',
        'ABVX':'Abivax',
        'SAVE.PA':'Savencia',
        'FNAC.PA':'Fnac Darty',
        'VALN':'Valneva',
        'ATO.PA':'Atos',
        'OLG.PA':'OL Groupe',
        'NBTX' : 'Nanobiotix',
        'CRI.PA':'Chargeurs',
        'CLARI.PA':'Clariane',
        'IPHA':'Innate Pharma',
        'CLLS':'Cellectis',
        'DBVT':'DBV Technologies',
        'SQNS':'Sequans',
        'ALERS.PA':'Eurobio',
        'NACON.PA':'Nacon',
        'SRP.PA':'Showroomprivé',
        'ALFOC.PA':'Focus',
        'MCPHY.PA':'McPhy Energy',
        'CO.PA':'Casino',
        'ALDNE.PA':'Dont Nod',
        'ALWIT.PA':'Witbe',
        'AB.PA':'AB Science',
        'ABCA.PA':'ABC Arbitrage',
        'BOI.PA':'Boiron',
        'BON.PA':'Bonduelle',
        'ELIOR.PA':'Elior',
        'IDL.PA':'ID Logistics',
        'JCQ.PA':'Jacquet Metal Service',
        'KOF.PA':'Kaufman & Broad',
        'LOUP.PA':'Linedata Services',
        'MERY.PA':'Mersen',
        'MDM.PA':'Maisons du Monde',
        'MAU.PA':'Maurel & Prom',
        'NXI.PA':'Nexity',
        'PEUG.PA':'Peugeot',
        'QDT.PA':'Quadient',
        'VAC.PA':'Pierre et Vacances',
        'ENGI.PA':'Engie',
        'EN.PA':'Bouygues',
        'STM':'STMicroelectronics',
        'MT.AS':'ArcelorMittal',
        'AYA.TO':'Aya Gold & Silver',
        '600489.SS':'Zhongjin Gold Corp.,LtdZhongjin Gold Corp.,Ltd',
        '601069.SS':'Western Region Gold Co., Ltd.',
        'CG.TO':'Centerra Gold Inc.',
        'ELO1.SG':'Eldorado Gold Corp.',
        'FVI.TO':'Fortuna Silver Mines Inc.',
        'SSL.TO':'Sandstorm Gold Ltd.',
        'OR':'Osisko Gold Royalties Ltd',
        'RGLD':'Royal Gold, Inc.',
        'WPM.TO':'Wheaton Precious Metals Corp.',
        'PSK.TO':'PrairieSky Royalty Ltd.',
        'FRU.TO':'Freehold Royalties Ltd.',
        'CNE.TO':'Canacol Energy Ltd',
        'ECOPETROL.CL':'Ecopetrol S.A.',
        'KOS':'Kosmos Energy Ltd.',
        'MEDC.JK':'Medco Energi Internasional Tbk.',
        'WDS':'Woodside Energy Group Ltd.',
        'AR':'Antero Resources Corp.',
        'CNQ.TO':'Canadian Natural Resources Ltd.',
        'ARLP':'Alliance Resource Partners, L.P.',
        'BRY':'Berry Corporation',
        '601918.SS':'China Coal Xinji Energy Co.,Ltd.',
        'YAL.AX':'Yancoal Australia Ltd.'
}
def translate_symbol(symbol):
            symbol = symbol.strip()
            if symbol in companies:
                return companies[symbol]
            else:
                return symbol

def translate_company(company):
    for key, value in companies.items():
        if value == company:
            return key
    return company